version: '3.8'

services:
  proofcast-core:
    image: proofcast-core:latest
    hostname: core
    container_name: proofcast-core
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
    volumes:
      - ./config:/app/config:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  proofcast-verifier:
    image: proofcast-verifier:latest
    hostname: verifier
    container_name: proofcast-verifier
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - CORE_SERVICE_URL=http://core:8080
      - LOG_LEVEL=info
    depends_on:
      proofcast-core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  proofcast-ui:
    # Собирается через Dockerfile: npm install && npm run build
    image: proofcast-ui:latest
    hostname: ui
    container_name: proofcast-ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_CORE_URL=http://localhost:8080
      - REACT_APP_VERIFIER_URL=http://localhost:8081
    depends_on:
      proofcast-core:
        condition: service_healthy
      proofcast-verifier:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

networks:
  default:
    driver: bridge
    name: proofcast-network